# Generated by Django 3.2.25 on 2024-07-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240726_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
