# Generated by Django 3.2.25 on 2024-07-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
