# Generated by Django 3.2.25 on 2024-07-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_description',
            field=models.CharField(max_length=400),
        ),
    ]
