# Generated by Django 3.2.25 on 2024-08-04 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_receipe_receipe_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='receipe_view_count',
        ),
    ]
