# Generated by Django 3.2.25 on 2024-08-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_remove_receipe_receipe_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
