# Generated by Django 3.2.25 on 2024-08-04 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_department_student_studentid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_age'], 'verbose_name': 'student'},
        ),
    ]
